# ; -*- mode: shell-script;-*-
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

setopt AUTO_PUSHD # cd does pushd
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME

alias wtf="git status"

commit_msg()    { curl whatthecommit.com 2>/dev/null | xmlstarlet sel -T -t -m '//div/p[1]' -v '.' }
excuse()        { curl programmerexcuses.com 2>/dev/null | grep -m 1 center | sed 's/<[^>]\+>//g;' }
gen_file_list() { find . -type f | sort | xargs sha1sum | tee file-list.txt }
# Enumerate processes in Disk Sleep ('D' in top)
ps_ds()         { top -b -n 1 | awk '{if (NR <=7) print; else if ($8 == "D") {print; count++} } END {print "Total status D: "count}' }
# Disk usage for compressed files
duc() {
    gzip -l $@ | awk 'END{print $2}' | numfmt --to=iec-i --suffix=B --format="%3f"
}

export IRCNICK="hut8"
export IRCNAME="Liam"
export IRCUSER="hut8"
export IRCSERVER="card.freenode.net"
export EMAIL="liambowen@gmail.com"
export GOPATH="$HOME/go"
export CSHEDIT="emacsclient -t"
export EDITOR="emacsclient -t"
export VISUAL="emacsclient -t"
export ALTERNATE_EDITOR=""
export PATH="$HOME/.local/bin:/usr/local/go/bin:$GOPATH/bin:/opt/google/chrome:$PATH:/usr/local/bin:/usr/bin:/bin:/usr/games:$HOME/.rvm/bin:/sbin:/usr/sbin"

export GHC_EVENTS_PATH="/github-archive/2015"
export GHC_TIMELINE_PATH="/github-archive/timeline"
export GHC_TRANSFORMED_PATH="/github-archive/transformed"
export GHC_LOADED_PATH="/github-archive/loaded"
export GHC_USERDB_PATH="/github-archive/userdb"
export GHC_LOG_PATH="/github-archive/logs"

[[ ! -d "$GOPATH" ]] && mkdir $GOPATH

if [ "$TERM" != "screen-256color" ] && [ "$TERM" != "fbterm" ] && [ "$TERM" != "linux" ]; then
    export TERM="xterm-256color"
fi

# Local preferences
[[ -f "$HOME/.zshrc-local" ]] && source "$HOME/.zshrc-local"
